const GLOBAL_ALL_TAGS_PRESENT = [
	"brute force",
	"dfs and similar",
	"dp",
	"implementation",
	"data structures",
	"math",
	"two pointers",
	"combinatorics",
	"binary search",
	"bitmasks",
	"hashing",
	"string suffix structures",
	"constructive algorithms",
	"greedy",
	"probabilities",
	"ternary search",
	"matrices",
	"geometry",
	"shortest paths",
	"interactive",
	"graphs",
	"games",
	"strings",
	"dsu",
	"trees",
	"*special",
	"sortings",
	"number theory",
	"flows",
	"graph matchings",
	"fft",
	"divide and conquer",
	"meet-in-the-middle",
	"expression parsing",
	"2-sat",
	"chinese remainder theorem",
	"schedules",
];
module.exports = GLOBAL_ALL_TAGS_PRESENT;
